name: photofilters
description: A flutter application that mimics Snapchat's lenses/filters using Firebase ML for face detection

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1

  # Firebase
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.11
  firebase_ml_vision: ^0.9.3+8

  # Utils
  scoped_model: ^1.0.1
  path_provider: ^1.6.7
  sqflite: ^1.3.0
  feature_discovery: ^0.8.0
  flutter_launcher_icons: ^0.7.3
  image_picker: ^0.6.5+3
  image_gallery_saver: ^1.2.2
  permission_handler: ^5.0.0+hotfix.5

  # Widgets
  flutter_circular_text: ^0.3.0
  flutter_swiper: ^1.1.6
  flutter_slidable: ^0.5.4
  flutter_camera_ml_vision: ^2.2.5
  flutter_speed_dial: ^1.2.5
  flutter_form_builder: ^3.9.0
  flutter_iconpicker: ^1.1.3

  page_slider: ^0.0.2
  carousel_slider: ^2.1.0

dependency_overrides:
  camera:
    git:
      url: git://github.com/hillelcoren/plugins.git
      path: packages/camera

flutter_icons:
  # Icons made by https://www.flaticon.com/authors/flat-icons
  android: true
  ios: true
  image_path: 'assets/icon.png'

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/preview.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
